"""Validation schemas for AI agent outputs.

All data generated by LLM agents must pass through these validators
before being persisted to the database.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Literal


class ValidatedRisk(BaseModel):
    title: str = Field(..., min_length=5, max_length=500)
    description: str = Field(..., min_length=10, max_length=5000)
    category: Literal["operational", "compliance", "security", "financial"]
    likelihood: int = Field(..., ge=1, le=5)
    impact: int = Field(..., ge=1, le=5)
    risk_score: int = Field(..., ge=1, le=25)
    risk_level: Literal["low", "medium", "high", "critical"]
    treatment_type: str = Field(default="mitigate", max_length=50)
    treatment_recommendation: str = Field(default="", max_length=5000)

    @field_validator("risk_score")
    @classmethod
    def validate_risk_score(cls, v, info):
        expected = info.data.get("likelihood", 1) * info.data.get("impact", 1)
        if v != expected:
            return expected
        return v


class ValidatedControl(BaseModel):
    title: str = Field(..., min_length=5, max_length=500)
    description: str = Field(default="", max_length=5000)
    implementation_details: str = Field(default="", max_length=5000)
    status: Literal["draft", "in_progress", "implemented", "not_implemented", "not_applicable", "needs_review"] = "draft"
    automation_level: Literal["manual", "semi_automated", "automated"] = "manual"
    test_procedure: str = Field(default="", max_length=5000)


class ValidatedPolicy(BaseModel):
    title: str = Field(..., min_length=5, max_length=500)
    content: str = Field(..., min_length=10, max_length=100000)
    version: str = Field(default="1.0", max_length=50)
    status: Literal["draft", "review", "approved", "published", "archived"] = "draft"


class ValidatedRemediation(BaseModel):
    control_id: str = Field(..., min_length=1)
    steps: list[str] = Field(..., min_length=1, max_length=20)
    priority: Literal["critical", "high", "medium", "low"]
    estimated_effort: str = Field(..., max_length=200)


class ValidatedAuditFinding(BaseModel):
    title: str = Field(..., min_length=5, max_length=500)
    description: str = Field(..., min_length=10, max_length=5000)
    severity: Literal["critical", "high", "medium", "low"]
    recommendation: str = Field(default="", max_length=5000)


class ValidatedVendorRisk(BaseModel):
    overall_score: int = Field(..., ge=0, le=100)
    risk_tier: Literal["critical", "high", "medium", "low"]
    risk_areas: list[dict] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)


class ValidatedMonitoringAlert(BaseModel):
    title: str = Field(..., min_length=5, max_length=500)
    severity: Literal["low", "medium", "high", "critical"]
    details: str = Field(default="", max_length=5000)


def validate_agent_output(data_list: list[dict], validator_class: type[BaseModel]) -> tuple[list, list]:
    """Validate a list of AI-generated items against a Pydantic model.

    Returns:
        (validated_items, validation_errors)
    """
    from pydantic import ValidationError

    validated = []
    errors = []
    for item in data_list:
        try:
            validated.append(validator_class(**item))
        except ValidationError as e:
            errors.append({
                "input": item.get("title", item.get("control_id", "unknown")),
                "errors": str(e),
            })
    return validated, errors
